image: ruby:2.3

variables:
  JEKYLL_ENV: production

pages:
  stage: deploy
  script:
  - bundle install
  - bundle exec jekyll build -d public
  - echo 'creating new pages'
  artifacts:
    paths:
    - public
  only:
  - gitlab-pages
  tags:
  - general

