# Site settings
title: Project Team gg
email: 
description: > # this means to ignore newlines until "baseurl:"
  Tiimi gg:n verkkosivu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prjteam-g.pages.labranet.jamk.fi/gg/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
